on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Token fun
      shell: pwsh
      permissions:
        id-token: write
      run: |
        Write-Host $env:ACTIONS_RUNTIME_TOKEN
        Write-Host $env:ACTIONS_ID_TOKEN_REQUEST_URL
