on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:

    - uses: joelverhagen/oidc-login@v0.1.0
      id: iodc-login

    - name: Token fun
      shell: pwsh
      run: |
        $info = $env:TOKEN_INFO | ConvertFrom-Json
        $url = "$($info.tokenUrl)&authority=$($info.authority)"
        $headers = @{
          Authorization = "Bearer $($info.runtimeToken)";
          Accept = "application/json; api-version=2.0";
          "Content-Type" = "application/json"
        }
        $resp = Invoke-WebRequest -Method POST $url -Headers $headers -Body "{}"
        $resp.Content | Out-File "resp.json" -Encoding utf8
      env:
        TOKEN_INFO: ${{ steps.iodc-login.outputs.token-info }}

    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: resp.json