on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
    - uses: actions/github-script@v6
      id: get_token
      timeout-minutes: 10
      with:
        debug: true
        script: |
          const token = process.env['ACTIONS_RUNTIME_TOKEN']
          const runtimeUrl = process.env['ACTIONS_ID_TOKEN_REQUEST_URL']
          core.setOutput('TOKEN', token.trim())
          core.setOutput('IDTOKENURL', runtimeUrl.trim())
    - name: Token fun
      shell: pwsh
      run: |
        Write-Host $env:TOKEN
        Write-Host $env:IDTOKENURL
      env:
        TOKEN: ${{ steps.script.outputs.TOKEN }}
        IDTOKENURL: ${{ steps.script.outputs.IDTOKENURL }}
