on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    # - name: Publish
    #   run: dotnet publish --output ~/.nuget/plugins/netcore/TestCredentialProvider

    - uses: joelverhagen/oidc-login@v0.4.0
      id: oidc-login
      with:
        username: jver
        package-source: https://jver-oidc.azurewebsites.net/api/v2/package

    - name: Try delete
      run: dotnet nuget delete Knapcode.TorSharp 2.15.0 -s https://jver-oidc.azurewebsites.net/api/v2/package --non-interactive
      env:
        NUGET_TOKEN_INFO: ${{ steps.oidc-login.outputs.token-info }}
        NUGET_DANGEROUS_NO_REDACT: true

    - run: ls -R ~/.nuget
      if: always()

    - run: cat TestCredentialProvider.log.txt
      if: always()

    - uses: actions/upload-artifact@v3
      with:
        name: my-log
        path: TestCredentialProvider.log.txt
      if: always()

