on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:

    - uses: joelverhagen/oidc-login@v0.1.0
      id: iodc-login

    - name: Token fun
      shell: pwsh
      run: |
        Write-Host $env:TOKEN_INFO
      env:
        TOKEN_INFO: ${{ steps.iodc-login.outputs.token-info }}
