on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
    - name: Token fun
      shell: pwsh
      run: |
        Write-Host $env:ACTIONS_RUNTIME_TOKEN
        Write-Host $env:ACTIONS_ID_TOKEN_REQUEST_URL
