on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
    - uses: actions/github-script@v6
      id: get_token
      timeout-minutes: 10
      with:
        debug: true
        script: |
          core.setOutput('TOKEN', process.env['ACTIONS_RUNTIME_TOKEN'])
          core.setOutput('URL', process.env['ACTIONS_ID_TOKEN_REQUEST_URL'])
    - name: Token fun
      shell: pwsh
      run: |
        Write-Host $env:ACTIONS_RUNTIME_TOKEN
        Write-Host $env:ACTIONS_ID_TOKEN_REQUEST_URL
      env:
        ACTIONS_RUNTIME_TOKEN: ${{ steps.get_token.outputs.TOKEN }}
        ACTIONS_ID_TOKEN_REQUEST_URL: ${{ steps.get_token.outputs.URL }}
